### ISSUE TITLE
Simplify use of configuration files

### ISSUE THREAD

**Issue by rmariuzzo** [x-team/unleash#260]
Currently, every developer needs to manually merge `config.dist.js` with `config.js`. Upgrading the `config-webpack-plugin` allow this through webpack compilation time.

**Comment by karolsojko** [comment]
@rmariuzzo I've changed my docker-compose file to look like this:

```
web:
  build: .
  volumes:
    - .:/var/www/unleash
  working_dir: /var/www/unleash
  ports:
    - 80:3000
  environment:
    skills_api_url: 'http://test.com'
webpack:
  build: .
  volumes_from:
    - web
  working_dir: /var/www/unleash
  command: webpack -w
  environment:
    skills_api_url: 'http://test.com'
```

and the app still calls the Skills API url from the config dist file instead of the environment variable - should it behave like this? This blocks https://github.com/x-team/unleash/pull/258 from merging to release on staging
